---
version: "3.9"

# Variables are stored in the .env file which contains the defaults if not set in the environment.

### YAML Anchors ###
x-environment: &environment
  environment:
    - PUID=${PUID:-1001}
    - PGID=${PGID:-2222}
    - UMASK=${UMASK:-002}
    - TZ=${TZ:-Australia/Melbourne}
    - DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1}
    - COMPOSE_DOCKER_CLI_BUILD=${COMPOSE_DOCKER_CLI_BUILD:-1}
    - PRINTER_USB_0=${PRINTER_USB_0:-/dev/3dprinter}
    - PRINTER_WEBCAM_0=${PRINTER_WEBCAM_0:-/dev/webcam}
    - CAMERA_DEV=$PRINTER_WEBCAM_0
    - LOCAL_TIME_FILE=${LOCAL_TIME_FILE:-/etc/localtime}
    - OCTOPRINT_VOLUME=${OCTOPRINT_VOLUME:-/octoprint}
    - ENABLE_MJPG_STREAMER=${ENABLE_MJPG_STREAMER:-true}
    - MJPG_STREAMER_INPUT=${MJPG_STREAMER_INPUT:--r 1920x1080 -f 30 -n}
# https://hotio.dev/pullio/
x-autoupdate: &autoupdate
  labels:
    - "org.hotio.pullio.update=true"

x-restart: &restart
  restart: unless-stopped

x-env-configs: &env-configs
  env_file:
    - .env
### END OF YAML ANCHORS ###

### Services ###

services:
###### 3D Printing ######

  octoprint:
    image: octoprint/octoprint:latest
    <<: [*autoupdate, *restart, *env-configs, *environment]
    #    profiles:
    #      - "octoprint"
    container_name: octoprint
    cap_add:
      - SYS_NICE
      # - MKNOD
      # - SYS_RAWIO
    ports:
      - ${PORT_octoprint:-7126}:80
      # - ${PORT_octoprint_webcam1:-7127}:8081
      # - ${PORT_octoprint_webcam2:-7128}:8082
    # A list of device names with their MAJOR and MINOR IDs can be obtained by running:
    # stat -c '%n major: %t minor: %T' /dev/*
    # privileged: true # Only ever use this as a LAST RESORT, NEVER in production and ALWAYS make sure cgroup rules are applied and set correctly!
    # device_cgroup_rules:
    #   - 'c 188:* rmw' # access to usb serial devices like /dev/ttyUSB0, /dev/ttyUSB1 etc... when using CH340 USB serial adapters with the MAJOR of 188
    #   - 'c 81:* rmw' # access to video and webcam devices like /dev/video0, /dev/video1 etc... when using Logitech webcams with the MAJOR of 81
    #   - 'c 1:3 rw' # access to /dev/null
    #   - 'c 1:5 rw' # access to /dev/zero
    #   - 'c 1:8 rw' # access to /dev/random
    #   - 'c 1:9 rw' # access to /dev/urandom
    devices:
      - ${PRINTER_USB_0:-/dev/3dprinter}:/dev/3dprinter
      # - ${PRINTER_WEBCAM_1:-/dev/webcam1}:/dev/webcam1  #  C920   ATTR{serial}=="FB5BC4FF"
      # - ${PRINTER_WEBCAM_2:-/dev/webcam2}:/dev/webcam2  #  C922   ATTR{serial}=="36D296DF"
    volumes:
      - ${LOCAL_TIME_FILE}:${LOCAL_TIME_FILE}:ro
      - ${OCTOPRINT_VOLUME}:/octoprint:rw
      - ${OCTOPRINT_VOLUME}/sam/run:/etc/services.d/mjpg-streamer/run
    # environment:
      # - ENABLE_MJPG_STREAMER=true
      # - CAMERA_DEV=/dev/webcam1
      # - CAMERA_DEV=/dev/webcam1,/dev/webcam2 #/dev/webcam1
      # - MJPG_STREAMER_INPUT=${MJPG_STREAMER_INPUT}
    # group_add:
    #   - dialout
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-m",
          "5",
          "-s",
          "-f",
          "-i",
          "http://localhost:${PORT_octoprint}/",
        ]
      interval: 15m
      timeout: 20s
      retries: 3
      start_period: 120s

###### END 3D Printing ######

