name: "Lint Shell Files"

on:
  pull_request:
    paths:
      - "**/*.sh"
      - "**/*.rc"
      - "!**/node_modules/**"
    branches:
      - main
      - master
      - "!repo-sync/**"
      - "!renovate/**"
      - "!update/pre-commit-hooks/**"
  workflow_dispatch:

jobs:
  shellcheck:
    name: lint-shell
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@22f96e34e9185b642c5567cc26d1df952f5c9d10 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          path: "."
          pattern: |
            *.sh
            *.rc
          exclude: |
            ./.git/*
            ./**/node_modules/*
          check_all_files_with_shebangs: false
          fail_on_error: false
          level: warning
          shellcheck_flags: "--external-sources"
